##--------------- alias ---------------##
alias grep='grep --color=auto'
alias ps='ps -f --sort=start_time'
alias rm='rm -i'
alias ls='ls --color=auto -X'
alias la='ls -a'
alias ll='ls -l'
alias l='ls -la'
alias ks='ls'
alias sl='ls'
alias vi='vim'
alias calc='calc.exe &'
alias ep='explorer.exe .'
alias minecraft='/mnt/s/Game/Minecraft.exe &'
