##--------------- alias ---------------##
alias rm='rm -i'
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias l='ls -al'
alias ks='ls'
alias sl='ls'
alias vi='vim'
alias calc='calc.exe &'
alias ep='explorer.exe .'
